#!/bin/sh
#
# A script to make you stop and pause when you're about
# to commit to `master`
#

BRANCH=$(git symbolic-ref --short HEAD)

if [ "$BRANCH" = "master" ]; then
  echo "[WARNING] Attempting to commit to master."
  echo "Making you stop to think about your life"
  sleep 5
fi
exit 0

